<a href="https://colab.research.google.com/github/LAXMANPANT123/python-projects/blob/laxman/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [1]:
import numpy as np

In [4]:
#1d array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
# 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
#zeros
print(np.zeros((2,3)))

#ones
print(np.ones((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# range

print(np.arange(0,10,2))

[0 2 4 6 8]


In [11]:
#linspace

print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# array properties
"""
print(arr2.shape)      # shape
print(arr2.ndim)       # number of dimensions
print(arr2.size)       # total elements
print(arr2.dtype)      # data type

"""

In [13]:
# indexing and slicing

arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[-1])
print(arr[1:4])      #1 is inclusive and 4 is exclusive

10
50
[20 30 40]


In [15]:
# 2D
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[0,1])
print(arr[:,1])

2
[2 5]


In [17]:
# mathematical operations

a= np.array([1,2,3])
b= np.array([1,2,3])

print(a+b)

print(a-b)
print(a*b)
print(a/b)

print(np.sqrt(a))
print(np.sum(a))
print(np.mean(a))
print(np.max(a))


[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
[1.         1.41421356 1.73205081]
6
2.0
3


In [18]:
# reshaping

arr=np.arange(1,10)
reshaped=arr.reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
